In [1]:
import pandas as pd

audience = pd.read_csv('Данные для тестового задания - Данные об аудитории.csv')

audience.head()

         date                               user_id  view_adverts
0  2023-11-11  8c020470-8461-11ed-83d0-552e8cc749d6            13
1  2023-11-18  5875f070-7b92-11ee-a6fb-8b298e83f4f7            14
2  2023-11-29  3c2d27c0-4fd6-11eb-b89f-2ffb31b67dd6            21
3  2023-11-29  234a96d0-ad16-11ed-a2e6-793ddfeeba1f            23
4  2023-11-29  4d07c180-644f-11eb-879c-b7c02edf4f37            12

In [2]:
audience.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16814 entries, 0 to 16813
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          16814 non-null  object
 1   user_id       16814 non-null  object
 2   view_adverts  16814 non-null  int64
dtypes: int64(1), object(2)
memory usage: 394.2+ KB

In [3]:
audience['date'] = pd.to_datetime(audience['date'])

In [4]:
mau = audience['user_id'].nunique()

mau

7639

In [5]:
dau_by_day = audience.groupby('date')['user_id'].nunique()

dau_by_day

date
2023-11-01    623
2023-11-02    649
2023-11-03    573
2023-11-04    343
2023-11-05    350
2023-11-06    660
2023-11-07    629
2023-11-08    600
2023-11-09    661
2023-11-10    583
2023-11-11    354
2023-11-12    377
2023-11-13    646
2023-11-14    687
2023-11-15    690
2023-11-16    639
2023-11-17    585
2023-11-18    412
2023-11-19    378
2023-11-20    711
2023-11-21    651
2023-11-22    608
2023-11-23    632
2023-11-24    595
2023-11-25    366
2023-11-26    372
2023-11-27    589
2023-11-28    610
2023-11-29    621
2023-11-30    620
Name: user_id, dtype: int64

In [6]:
avg_dau = dau_by_day.mean()

avg_dau

np.float64(560.4666666666667)

In [7]:
nov_1_users = audience[audience['date'] == '2023-11-01']['user_id'].unique()

nov_2_users = audience[audience['date'] == '2023-11-02']['user_id'].unique()

returned_users = len(set(nov_1_users) & set(nov_2_users))

retention_day_1 = returned_users / len(nov_1_users) * 100

retention_day_1

26.64526484751204

In [8]:
users_with_adverts = audience[audience['view_adverts'] > 0]['user_id'].nunique()

conversion_to_adverts = users_with_adverts / mau * 100

conversion_to_adverts

46.31496269145176

In [9]:
total_adverts = audience['view_adverts'].sum()

avg_adverts_per_user = total_adverts / mau

avg_adverts_per_user

np.float64(2.8687000916350307)

In [11]:
ab_tests = pd.read_csv('Данные для тестового задания - Данные АБ тестов.csv')

ab_tests.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [12]:
ab_tests.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2835 entries, 0 to 2834
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   experiment_num    2835 non-null   int64
 1   experiment_group  2835 non-null   object
 2   user_id           2835 non-null   int64
 3   revenue           2835 non-null   int64
dtypes: int64(3), object(1)
memory usage: 88.7+ KB

In [15]:
ab_tests['experiment_group'].unique()

array(['test', 'control'], dtype=object)

In [16]:
from scipy.stats import ttest_ind

for exp in sorted(ab_tests['experiment_num'].unique()):
    test_data = ab_tests[ab_tests['experiment_num'] == exp]
    
    group_control = test_data[test_data['experiment_group'] == 'control']['revenue']
    group_test = test_data[test_data['experiment_group'] == 'test']['revenue']
    
    stat, p_value = ttest_ind(group_control, group_test, equal_var=False)
    
    print('Эксперимент:', exp)
    print('ARPU control:', group_control.mean())
    print('ARPU test:', group_test.mean())
    print('p-value:', p_value)
    print()

Эксперимент: 1
ARPU control: 722.4602150537635
ARPU test: 665.7395833333334
p-value: 0.688966190624939

Эксперимент: 2
ARPU control: 704.6537634408602
ARPU test: 332.9291666666667
p-value: 0.0011282266247294027

Эксперимент: 3
ARPU control: 663.2064516129033
ARPU test: 998.66875
p-value: 0.06031548002841902

In [17]:
listeners = pd.read_csv('Данные для тестового задания - Листеры.csv')

listeners.head()

   user_id        date  cnt_adverts  age  cnt_contacts  revenue
0      100  2022-01-01            6   21           119       53
1      100  2022-01-02            2   21           200       18
2      100  2022-01-03            6   21           193       42
3      100  2022-01-04            2   21           143       38
4      100  2022-01-05            2   21           190       40

In [18]:
listeners.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       158 non-null    int64
 1   date          158 non-null    object
 2   cnt_adverts   158 non-null    int64
 3   age           158 non-null    int64
 4   cnt_contacts  158 non-null    int64
 5   revenue       158 non-null    int64
dtypes: int64(5), object(1)
memory usage: 7.5+ KB

In [19]:
listeners.head()

   user_id        date  cnt_adverts  age  cnt_contacts  revenue
0      100  2022-01-01            6   21           119       53
1      100  2022-01-02            2   21           200       18
2      100  2022-01-03            6   21           193       42
3      100  2022-01-04            2   21           143       38
4      100  2022-01-05            2   21           190       40

In [20]:
revenue_by_user = listeners.groupby('user_id')['revenue'].sum()

avg_revenue_per_user = revenue_by_user.mean()

avg_revenue_per_user

np.float64(156.48387096774192)

In [21]:
age_by_user = listeners.drop_duplicates('user_id')[['user_id', 'age']]

median_age = age_by_user['age'].median()

median_age

28.0

In [22]:
from statsmodels.stats.proportion import proportions_ztest

payments = [1003, 1099]
visitors = [100047501, 100001055]

stat, p_value = proportions_ztest(payments, visitors)

conversion_a = payments[0] / visitors[0] * 100
conversion_b = payments[1] / visitors[1] * 100

print('Конверсия A:', conversion_a)
print('Конверсия B:', conversion_b)
print('p-value:', p_value)

Конверсия A: 0.0010025237911739544
Конверсия B: 0.0010989884056723201
p-value: 0.03533044544854254